### ISSUE TITLE
Wizard for sending emails based on emotions detected

### ISSUE THREAD

**Issue by josemariar** [EyesOfThings/Mobile_Camera_Demonstrator#16]
The webapp has a Wizard section. This section sends e-mails according to some rules defined by the user.  Considering that the WebApp is only able to recognize the detected emotions when the user uploads all captured images to the WebApp, makes sense to have the Wizard on the webapp?. In this case and if the wizard is activated, it can send several e-mails at the same time, one per image uploaded. To send emails in real time, the wizard should be implemented in the Android Applications, like the push notifications

**Comment by ijunaid8989** [comment]
@marcoherbst  it's best to have it on android application instead of the web app, the web app is collecting jpegs from firebase, It doesn't know when a jpeg is being uploaded but the android application does.

Another possible solution could create cloud function to trigger on any new upload to storage or entry to the database. This will need a new application for sure because current setup is in Ruby On Rails and Cloud Method SDK is for NodeJS not plan javascript.

**Comment by marcoherbst** [comment]
I suggest:

In order to get this done, we will build it on cloud side with triggers (NodeJS probably).
It will be one-by-one (not batch) as that's easier

@ijunaid8989 will keep this on his list @ Low Priority

**Comment by ijunaid8989** [comment]
Its done.
